### ISSUE TITLE
Support hasMultiple

### ISSUE THREAD

**Issue by HLeithner** [reactphp/cache#46]
I know it's not part of PSR-16 and sadly I don't know why because some cache controller could benefit from this function.

I would expect that's for a simple cache like ArrayCache it would be a simple loop on all values. The same using `all($getArray);` would be an overkill and I would expect an performance impact.

If no plans to add it I'm happy too.

**Comment by clue** [comment]
@HLeithner Thanks for bringing this up, this is an interesting one! :+1: 

Can you elaborate why you think having this would be beneficial?

It's my understanding the `has()` method should not be used for most common use cases as it would be subject to a race condition. I'm curious what your use case is and to see whether this could be better solved by using the `get()` or `getMultiple()` method instead.

> NOTE: It is recommended that has() is only to be used for cache warming type purposes and not to be used within your live applications operations for get/set, as this method is subject to a race condition where your has() will return true and immediately after, another script can remove it making the state of your app out of date.

**Comment by WyriHaximus** [comment]
> It's my understanding the `has()` method should not be used for most common use cases as it would be subject to a race condition. I'm curious what your use case is and to see whether this could be better solved by using the `get()` or `getMultiple()` method instead.
> 
> > NOTE: It is recommended that has() is only to be used for cache warming type purposes and not to be used within your live applications operations for get/set, as this method is subject to a race condition where your has() will return true and immediately after, another script can remove it making the state of your app out of date.

On top of that it also saves you doing an extra operation and sometimes, you get `has` for free when doing `get` and the item you want can't be found.

**Comment by HLeithner** [comment]
I have an index that get periodically updated something like this pseudo code:

```php

$array = $cache->get('messagesById-4711');

$cache->hasMultiple($array)->then(
  function($results) {
    $newIndex = [];
    foreach($results as $key => $exists) {
      if ($exists) $newIndex[] = $key;
    }
    $cache->set('messagesById-4711', $newIndex);
});
```

Now I would need to get the value which maybe expensive depending on the size of the entry or have to run each key within it's own request which is also expensive.

I also know that I would need to lock the index in the meantime while updating all indexes.

current code handles a non existing entry automatically but would to request it from the cache every time. So I basically build 
a for expired items to sync

**Comment by clue** [comment]
@HLeithner This is an interesting use case, thanks for sharing!

> Now I would need to get the value which maybe expensive depending on the size of the entry or have to run each key within it's own request which is also expensive.

This is particularly interesting. Which cache implementation do you happen to use here? This seems to be relevant to better discuss what "expensive" means and how this could be avoided with the help of this method.

For instance, for the built-in `ArrayCache` neither of these concerns matter because it's a simple, synchronous implementation anyway and there's little potential for optimization.

Likewise, any Redis-based cache implementation would have to use `EXISTS` for each individual key anyway, so there's little potential for optimization here as well.

I see this feature was briefly discussed in the PSR-16 review period https://groups.google.com/g/php-fig/c/kSj_yVbkwOw/m/lD4yHVE7BgAJ. While I agree the interface may looks slightly inconsistent without this method, I agree with the reasoning that adding this method (with regards to checking *any*, *all* or an array as suggested) as part of the interface would likely be overdoing it for most implementations.

Adding a new method to the interface would be considered a BC break, so I'd like to have a good understanding of the pros of this approach. At the moment, I'm not sure the pros outweigh the cons and wonder if a specific implementing for your particular use case would be more applicable?

**Comment by clue** [comment]
I'm closing this for now as it hasn't received any input in a while and I believe this has been answered. Please come back with more details if this is still an issue to you and we can always reopen this :+1:
